---

- name: add domain controller private IP as DNS server
  win_dns_client:
    adapter_names: "*"
    ipv4_addresses: "{{ dns_servers | default([]) }}"

- name: add windows server to the domain
  win_domain_membership:
    dns_domain_name: "{{ dns_domain_name }}"
    domain_admin_user: "{{ domain_admin_username }}@{{ dns_domain_name }}"
    domain_admin_password: "{{ domain_admin_password }}"
    state: domain
  register: join_domain

#- name: add a powershell module
#  win_psmodule:
#    name: xComputerManagement
#    state: present
#
#- name: add windows server to the domain
#  win_dsc:
#    resource_name: xComputer
#    Name: "{{ ansible_hostname }}"
#    DomainName: "{{ dns_domain_name }}"
#    JoinOU: '{{ join_ou_path | default("") }}'
#    credential_username: "{{ domain_admin_username }}@{{ dns_domain_name }}"
#    credential_password: "{{ domain_admin_password }}"
#  register: join_domain

- name: reboot server if required
  win_reboot:
  when: join_domain.reboot_required

#- name: set DNS search string
#  win_dns_searchsuffix:
#    suffixes:
#      - "{{ dns_domain_name }}"