---

# https://www.stigviewer.com/stig/windows_10/2016-11-03/finding/V-63373
- name: Permissions for system files and directories must conform to minimum requirements. - C
  win_acl:
    path: C:\
    user: "{{ item.u }}"
    rights: "{{ item.r }}"
    type: "{{ item.t }}"
    state: present
    inherit: "{{ item.i }}"
    propagation: "{{ item.p }}"
  loop:
    #- { u: 'Administrators', r: 'FullControl', t: 'allow', i: 'ContainerInherit, ObjectInherit', p: 'InheritOnly', s: present }
    #- { u: 'SYSTEM', r: 'FullControl', t: 'allow', i: 'ContainerInherit, ObjectInherit', p: 'InheritOnly', s: present }
    #- { u: 'Users', r: 'ReadAndExecute', t: 'allow', i: 'ContainerInherit, ObjectInherit', p: 'InheritOnly', s: present }
    - { u: 'Authenticated Users', r: 'Modify', t: 'allow', i: 'ContainerInherit, ObjectInherit', p: 'InheritOnly', s: present }
    - { u: 'Users', r: 'CreateDirectories, AppendData', t: 'allow', i: 'None', p: 'NoPropagateInherit', s: absent }
  register: check_c_acl

- name: Disable Remote Desktop
  win_regedit:
    key: 'HKLM:\System\CurrentControlSet\Control\Terminal Server'
    value: fDenyTSConnections
    data: 1
    datatype: dword
  register: check_rdp_disable

- fail:
    msg: "There is a drift in rdp configuration - failing"
  when:
    - fail_on_drift
    - check_rdp_disable is changed