---
- name: download PsTools
  win_get_url:
    dest: "{{ ansible_env.TEMP }}\\pstools.zip"
    url: "https://download.sysinternals.com/files/PSTools.zip"

- name: extract PSTools
  win_unzip:
    src: "{{ ansible_env.TEMP }}\\pstools.zip"
    dest: "{{ ansible_env.TEMP }}\\pstools"
    rm: true

- name: install SQL 2016
  win_psexec:
    command: "{{ disk_image_out.mount_path }}setup.exe /Q /ACTION=Install /IACCEPTSQLSERVERLICENSETERMS /ENU /UPDATEENABLED=false /FEATURES=SQLENGINE,Conn /INSTANCENAME=MSSQLSERVER /SECURITYMODE=SQL /SAPWD={{ mssql_password }} /AGTSVCSTARTUPTYPE=automatic /BROWSERSVCSTARTUPTYPE=automatic /SQLSYSADMINACCOUNTS={{ mssql_username }} /SQLBACKUPDIR=C:\\Backup /SQLUSERDBDIR=C:\\Databases /SQLUSERDBLOGDIR=C:\\UserDatabases"
    priority: high
    executable: "{{ ansible_env.TEMP }}\\pstools\\PsExec.exe"